In [1]:
import os
import pandas as pd

# listing files in data folder
print("Looking in 'data/':", os.listdir('data'))

Looking in 'data/': ['amsterdam_weekdays.csv', 'barcelona_weekends.csv', 'rome_weekdays.csv', 'berlin_weekdays.csv', 'budapest_weekdays.csv', 'vienna_weekdays.csv', 'london_weekdays.csv', 'lisbon_weekends.csv', 'athens_weekends.csv', 'paris_weekends.csv', 'barcelona_weekdays.csv', 'berlin_weekends.csv', 'rome_weekends.csv', 'amsterdam_weekends.csv', 'athens_weekdays.csv', 'paris_weekdays.csv', 'vienna_weekends.csv', 'budapest_weekends.csv', 'lisbon_weekdays.csv', 'london_weekends.csv']

In [2]:
# loading one dataset, Amsterdam Weekdays
df = pd.read_csv('data/amsterdam_weekdays.csv')

In [3]:
# preview  first 5 rows
display(df.head())

,Unnamed: 0,realSum,room_type,room_shared,room_private,person_capacity,host_is_superhost,multi,biz,cleanliness_rating,guest_satisfaction_overall,bedrooms,dist,metro_dist,attr_index,attr_index_norm,rest_index,rest_index_norm,lng,lat
0,0,194.033698,Private room,False,True,2.0,False,1,0,10.0,93.0,1,5.022964,2.539380,78.690379,4.166708,98.253896,6.846473,4.90569,52.41772
1,1,344.245776,Private room,False,True,4.0,False,0,0,8.0,85.0,1,0.488389,0.239404,631.176378,33.421209,837.280757,58.342928,4.90005,52.37432
2,2,264.101422,Private room,False,True,2.0,False,0,1,9.0,87.0,1,5.748312,3.651621,75.275877,3.985908,95.386955,6.646700,4.97512,52.36103
3,3,433.529398,Private room,False,True,4.0,False,0,1,9.0,90.0,2,0.384862,0.439876,493.272534,26.119108,875.033098,60.973565,4.89417,52.37663
4,4,485.552926,Private room,False,True,2.0,True,0,0,10.0,98.0,1,0.544738,0.318693,552.830324,29.272733,815.305740,56.811677,4.90051,52.37508

In [4]:
# check the dimensions (Rows, Columns)
print(f"Dataset shape: {df.shape}")

Dataset shape: (1103, 20)

In [5]:
#check data types and mising values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1103 entries, 0 to 1102
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Unnamed: 0                  1103 non-null   int64
 1   realSum                     1103 non-null   float64
 2   room_type                   1103 non-null   object
 3   room_shared                 1103 non-null   bool
 4   room_private                1103 non-null   bool
 5   person_capacity             1103 non-null   float64
 6   host_is_superhost           1103 non-null   bool
 7   multi                       1103 non-null   int64
 8   biz                         1103 non-null   int64
 9   cleanliness_rating          1103 non-null   float64
 10  guest_satisfaction_overall  1103 non-null   float64
 11  bedrooms                    1103 non-null   int64
 12  dist                        1103 non-null   float64
 13  metro_dist                  1103 non-null   float64
 14  attr_index                  1103 non-null   float64
 15  attr_index_norm             1103 non-null   float64
 16  rest_index                  1103 non-null   float64
 17  rest_index_norm             1103 non-null   float64
 18  lng                         1103 non-null   float64
 19  lat                         1103 non-null   float64
dtypes: bool(3), float64(12), int64(4), object(1)
memory usage: 149.8+ KB

In [6]:
# exploring individual column
df['room_type'].value_counts()

room_type
Private room       559
Entire home/apt    538
Shared room          6
Name: count, dtype: int64

In [7]:
# looking for pricing outliers. realSum is total price of listing
df[['realSum', 'dist', 'metro_dist']].describe()

           realSum         dist   metro_dist
count  1103.000000  1103.000000  1103.000000
mean    545.020526     2.841621     1.089439
std     416.974314     2.123245     0.836546
min     128.887118     0.015059     0.036530
25%     309.797764     1.302058     0.462983
50%     430.248635     2.341366     0.856010
75%     657.324303     3.648138     1.510629
max    7782.907225    11.187100     4.411915

In [8]:
# checking for nulls in each column
print(df.isna().sum())

Unnamed: 0                    0
realSum                       0
room_type                     0
room_shared                   0
room_private                  0
person_capacity               0
host_is_superhost             0
multi                         0
biz                           0
cleanliness_rating            0
guest_satisfaction_overall    0
bedrooms                      0
dist                          0
metro_dist                    0
attr_index                    0
attr_index_norm               0
rest_index                    0
rest_index_norm               0
lng                           0
lat                           0
dtype: int64

In [9]:
# checking for duplicates
df.duplicated().sum()

np.int64(0)

In [17]:
# filtering only listings with guest ratings over 90
high_rated_df = df[df['guest_satisfaction_overall'] > 90 ]
high_rated_df.head()

,Unnamed: 0,total_listing_price,room_type,room_shared,room_private,person_capacity,host_is_superhost,multi,biz,cleanliness_rating,guest_satisfaction_overall,bedrooms,dist,metro_dist,attr_index,attr_index_norm,rest_index,rest_index_norm,lng,lat
0,0,194.033698,Private room,False,True,2.0,False,1,0,10.0,93.0,1,5.022964,2.539380,78.690379,4.166708,98.253896,6.846473,4.90569,52.41772
4,4,485.552926,Private room,False,True,2.0,True,0,0,10.0,98.0,1,0.544738,0.318693,552.830324,29.272733,815.305740,56.811677,4.90051,52.37508
5,5,552.808567,Private room,False,True,3.0,False,0,0,8.0,100.0,2,2.131420,1.904668,174.788957,9.255191,225.201662,15.692376,4.87699,52.38966
6,6,215.124317,Private room,False,True,2.0,False,0,0,10.0,94.0,1,1.881092,0.729747,200.167652,10.599010,242.765524,16.916251,4.91570,52.38296
7,7,2771.307384,Entire home/apt,False,False,4.0,True,0,0,10.0,100.0,3,1.686807,1.458404,208.808109,11.056528,272.313823,18.975219,4.88467,52.38749

In [ ]:
#renaming realSum, multi, and biz columns
df = df.rename(columns={
    'realSum': 'total_listing_price', 
    'multi': 'is_multi_listing', 
    'biz': 'is_business_listing' 
    })

#verifying name change
print(df.columns)

Index(['total_listing_price', 'room_type', 'room_shared', 'room_private',
       'person_capacity', 'host_is_superhost', 'is_multi_listing',
       'is_business_listing', 'cleanliness_rating',
       'guest_satisfaction_overall', 'bedrooms', 'dist', 'metro_dist',
       'attr_index', 'attr_index_norm', 'rest_index', 'rest_index_norm', 'lng',
       'lat'],
      dtype='object')

In [29]:
#dropping column Unnamed: 0 if it exists, if not, no error is raised
df = df.drop(columns=['Unnamed: 0'], errors='ignore')

#verifying drop
df.head()

,total_listing_price,room_type,room_shared,room_private,person_capacity,host_is_superhost,is_multi_listing,is_business_listing,cleanliness_rating,guest_satisfaction_overall,bedrooms,dist,metro_dist,attr_index,attr_index_norm,rest_index,rest_index_norm,lng,lat
0,194.033698,Private room,False,True,2.0,False,1,0,10.0,93.0,1,5.022964,2.539380,78.690379,4.166708,98.253896,6.846473,4.90569,52.41772
1,344.245776,Private room,False,True,4.0,False,0,0,8.0,85.0,1,0.488389,0.239404,631.176378,33.421209,837.280757,58.342928,4.90005,52.37432
2,264.101422,Private room,False,True,2.0,False,0,1,9.0,87.0,1,5.748312,3.651621,75.275877,3.985908,95.386955,6.646700,4.97512,52.36103
3,433.529398,Private room,False,True,4.0,False,0,1,9.0,90.0,2,0.384862,0.439876,493.272534,26.119108,875.033098,60.973565,4.89417,52.37663
4,485.552926,Private room,False,True,2.0,True,0,0,10.0,98.0,1,0.544738,0.318693,552.830324,29.272733,815.305740,56.811677,4.90051,52.37508

In [26]:
#sorting most expensive listings first
sorted_df = df.sort_values(by='total_listing_price', ascending=False)
sorted_df.head()

,total_listing_price,room_type,room_shared,room_private,person_capacity,host_is_superhost,multi,biz,cleanliness_rating,guest_satisfaction_overall,bedrooms,dist,metro_dist,attr_index,attr_index_norm,rest_index,rest_index_norm,lng,lat
970,7782.907225,Entire home/apt,False,False,6.0,False,1,0,10.0,100.0,3,2.980734,2.039112,127.319506,6.741652,171.558121,11.954417,4.89500,52.40000
133,3637.663159,Entire home/apt,False,False,4.0,False,0,0,10.0,97.0,3,0.724211,0.186370,442.952234,23.454615,540.705525,37.677139,4.90355,52.37202
99,3004.944579,Entire home/apt,False,False,4.0,False,0,0,9.0,95.0,4,1.615295,1.402539,216.669036,11.472769,283.617712,19.762890,4.88478,52.38683
7,2771.307384,Entire home/apt,False,False,4.0,True,0,0,10.0,100.0,3,1.686807,1.458404,208.808109,11.056528,272.313823,18.975219,4.88467,52.38749
158,2556.183067,Entire home/apt,False,False,6.0,True,1,0,10.0,99.0,3,0.970919,1.096036,432.551184,22.903873,512.237797,35.693467,4.88093,52.37778

In [ ]:
# checking data types
print(df.dtypes)

#if 'is_multi_listing' or 'is_business_listing' are not boolean, convert:
df['is_multi_listing'] = df['is_multi_listing'].astype(bool)
df['is_business_listing'] = df['is_business_listing'].astype(bool)

# confirming data type changes
print(df.types)

total_listing_price           float64
room_type                      object
room_shared                      bool
room_private                     bool
person_capacity               float64
host_is_superhost                bool
is_multi_listing                int64
is_business_listing             int64
cleanliness_rating            float64
guest_satisfaction_overall    float64
bedrooms                        int64
dist                          float64
metro_dist                    float64
attr_index                    float64
attr_index_norm               float64
rest_index                    float64
rest_index_norm               float64
lng                           float64
lat                           float64
dtype: object

In [32]:
# summary: grouping by room type to see average price and satisfaction
# of weekday Airbnb bookings in Amsterdam

summary = df.groupby('room_type')[['total_listing_price', 'guest_satisfaction_overall']].mean()
print(summary)

                 total_listing_price  guest_satisfaction_overall
room_type
Entire home/apt           733.179099                   95.211896
Private room              366.764655                   93.561717
Shared room               280.973918                   92.833333